### ISSUE TITLE
How to configure the github, facebook oauth2's info?

### ISSUE THREAD

**Issue by dsonet** [arangodb-foxx/demo-sessions#3]
I can't find a way to do that.
Or can't reuse the OAuth2 Client?
Thanks.

**Comment by caerus706** [comment]
Try adding the service 3 times to 3 different endpoints, then just configure each to it's respective service.

**Comment by dsonet** [comment]
Ya, that exactly what I tried, just curious if there is a better way to achieve this.

**Comment by pluma** [comment]
@dsonet no, each installed service represents one provider.

We're overhauling this for ArangoDB 3.0 and will likely provide OAuth2 out of the box without the need to install the OAuth2 service.
